[package]
name = "fit-dashboard-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argon2 = "0.5"
axum = { version = "0.8", features = ["multipart"] }
chrono = { version = "0.4", features = ["serde"] }
duckdb = { version = "1.2", features = ["bundled"] }
dirs = "5"
fitparser = "0.8"
hex = "0.4"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"], optional = true }
rusqlite = { version = "0.31", features = ["bundled"] }
reverse_geocoder = "4.1.1"
roxmltree = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "fs"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tauri = { version = "2", optional = true , features = ["image-png"] }
tauri-plugin-dialog = { version = "2", optional = true }
tauri-plugin-shell = { version = "2.3.5", optional = true }

[build-dependencies]
tauri-build = { version = "2", features = [] }
static_vcruntime = "2"

# Optional desktop mode
# tauri and tauri-plugin-shell can be enabled if you want to compile desktop binaries immediately.

[features]
default = ["web"]
web = ["dep:reqwest"]
tauri-app = ["dep:tauri", "dep:tauri-plugin-dialog", "dep:tauri-plugin-shell"]
